# Accessing the LLS dataset

In [1]:
import biu

## Initializing and examining the structure
The phenotypes data file is not located in a reasonable location. We must provide our own local copy of it.

In [2]:
lls = biu.db.LLS(localCopy={"phen" : "/home/tgehrmann/repos/VAR/phen218.txt"})
print(lls)

LLS object
 Where: /exports/molepi/LLSSEQ
 Version: current
 Objects:
  * [ ] phenotypes
  * [ ] vcf[1]
  * [ ] vcf[2]
  * [ ] vcf[3]
  * [ ] vcf[4]
  * [ ] vcf[5]
  * [ ] vcf[6]
  * [ ] vcf[7]
  * [ ] vcf[8]
  * [ ] vcf[9]
  * [ ] vcf[10]
  * [ ] vcf[11]
  * [ ] vcf[12]
  * [ ] vcf[13]
  * [ ] vcf[14]
  * [ ] vcf[15]
  * [ ] vcf[16]
  * [ ] vcf[17]
  * [ ] vcf[18]
  * [ ] vcf[19]
  * [ ] vcf[20]
  * [ ] vcf[21]
  * [ ] vcf[22]
  * [ ] vcf[M]
  * [ ] vcf[X]
  * [ ] vcf[Y]
 Files:
  * [X] vcf_1 : /exports/molepi/LLSSEQ/tbx/merged.chr1.vcf.bgz
  * [X] vcf_1_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr1.vcf.bgz.tbi
  * [X] vcf_2 : /exports/molepi/LLSSEQ/tbx/merged.chr2.vcf.bgz
  * [X] vcf_2_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr2.vcf.bgz.tbi
  * [X] vcf_3 : /exports/molepi/LLSSEQ/tbx/merged.chr3.vcf.bgz
  * [X] vcf_3_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr3.vcf.bgz.tbi
  * [X] vcf_4 : /exports/molepi/LLSSEQ/tbx/merged.chr4.vcf.bgz
  * [X] vcf_4_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr4.vcf.bgz.tbi
  * [X] vcf_5 : /exports/molepi/LLSSEQ/tbx/merged.chr5.vcf.bgz
  * [X] vcf_5_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr5.vcf.bgz.tbi
  * [X] vcf_6 : /exports/molepi/LLSSEQ/tbx/merged.chr6.vcf.bgz
  * [X] vcf_6_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr6.vcf.bgz.tbi
  * [X] vcf_7 : /exports/molepi/LLSSEQ/tbx/merged.chr7.vcf.bgz
  * [X] vcf_7_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr7.vcf.bgz.tbi
  * [X] vcf_8 : /exports/molepi/LLSSEQ/tbx/merged.chr8.vcf.bgz
  * [X] vcf_8_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr8.vcf.bgz.tbi
  * [X] vcf_9 : /exports/molepi/LLSSEQ/tbx/merged.chr9.vcf.bgz
  * [X] vcf_9_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr9.vcf.bgz.tbi
  * [X] vcf_10 : /exports/molepi/LLSSEQ/tbx/merged.chr10.vcf.bgz
  * [X] vcf_10_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr10.vcf.bgz.tbi
  * [X] vcf_11 : /exports/molepi/LLSSEQ/tbx/merged.chr11.vcf.bgz
  * [X] vcf_11_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr11.vcf.bgz.tbi
  * [X] vcf_12 : /exports/molepi/LLSSEQ/tbx/merged.chr12.vcf.bgz
  * [X] vcf_12_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr12.vcf.bgz.tbi
  * [X] vcf_13 : /exports/molepi/LLSSEQ/tbx/merged.chr13.vcf.bgz
  * [X] vcf_13_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr13.vcf.bgz.tbi
  * [X] vcf_14 : /exports/molepi/LLSSEQ/tbx/merged.chr14.vcf.bgz
  * [X] vcf_14_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr14.vcf.bgz.tbi
  * [X] vcf_15 : /exports/molepi/LLSSEQ/tbx/merged.chr15.vcf.bgz
  * [X] vcf_15_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr15.vcf.bgz.tbi
  * [X] vcf_16 : /exports/molepi/LLSSEQ/tbx/merged.chr16.vcf.bgz
  * [X] vcf_16_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr16.vcf.bgz.tbi
  * [X] vcf_17 : /exports/molepi/LLSSEQ/tbx/merged.chr17.vcf.bgz
  * [X] vcf_17_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr17.vcf.bgz.tbi
  * [X] vcf_18 : /exports/molepi/LLSSEQ/tbx/merged.chr18.vcf.bgz
  * [X] vcf_18_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr18.vcf.bgz.tbi
  * [X] vcf_19 : /exports/molepi/LLSSEQ/tbx/merged.chr19.vcf.bgz
  * [X] vcf_19_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr19.vcf.bgz.tbi
  * [X] vcf_20 : /exports/molepi/LLSSEQ/tbx/merged.chr20.vcf.bgz
  * [X] vcf_20_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr20.vcf.bgz.tbi
  * [X] vcf_21 : /exports/molepi/LLSSEQ/tbx/merged.chr21.vcf.bgz
  * [X] vcf_21_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr21.vcf.bgz.tbi
  * [X] vcf_22 : /exports/molepi/LLSSEQ/tbx/merged.chr22.vcf.bgz
  * [X] vcf_22_tbi : /exports/molepi/LLSSEQ/tbx/merged.chr22.vcf.bgz.tbi
  * [X] vcf_M : /exports/molepi/LLSSEQ/tbx/merged.chrM.vcf.bgz
  * [X] vcf_M_tbi : /exports/molepi/LLSSEQ/tbx/merged.chrM.vcf.bgz.tbi
  * [X] vcf_X : /exports/molepi/LLSSEQ/tbx/merged.chrX.vcf.bgz
  * [X] vcf_X_tbi : /exports/molepi/LLSSEQ/tbx/merged.chrX.vcf.bgz.tbi
  * [X] vcf_Y : /exports/molepi/LLSSEQ/tbx/merged.chrY.vcf.bgz
  * [X] vcf_Y_tbi : /exports/molepi/LLSSEQ/tbx/merged.chrY.vcf.bgz.tbi
  * [X] phen : /home/tgehrmann/repos/VAR/phen218.txt

D: Could not make Symbolic link for 'phen'. Rewriting internal location.

## Querying the structure

With the exception of the list of participants, the data held in LLS are tabix indexed VCF files. Thus, we can make use of the `query` and `queryRegions` functionalities of the VCF structures.

### Examining the list of participants
The `phenotypes` object of the lls structure describes the list of participants

In [11]:
lls.phenotypes[(lls.phenotypes["sex"] == "MALE") & (lls.phenotypes["age"] > 100) ]

                cgID            cgID2        LLnr  labnr         age   sex
1    GS00354-DNA_B01  GS000002814-ASM  005.2.01.0      6  100.974675  MALE
52   GS00354-DNA_F07  GS000002795-ASM  112.2.02.0    695  102.193018  MALE
188  GS00398-DNA_C02  GS000003087-ASM  429.2.01.0   2822  100.517454  MALE
196  GS00398-DNA_B01  GS000002935-ASM  441.2.02.0   2740  101.141684  MALE
211  GS00398-DNA_C03  GS000003081-ASM  468.2.02.0   2895  100.183436  MALE

### Querying the variants

In [7]:
for record in lls.query(1, 1000000, 1001000, types=['snp']):
    print(record)

Record(CHROM=1, POS=1000760, REF=G, ALT=[A])
Record(CHROM=1, POS=1000797, REF=C, ALT=[T])
Record(CHROM=1, POS=1000854, REF=A, ALT=[C])
Record(CHROM=1, POS=1000857, REF=G, ALT=[T])
Record(CHROM=1, POS=1000894, REF=A, ALT=[T])
Record(CHROM=1, POS=1000902, REF=G, ALT=[A])
Record(CHROM=1, POS=1000910, REF=C, ALT=[T])
Record(CHROM=1, POS=1000987, REF=T, ALT=[C])
Record(CHROM=1, POS=1000990, REF=T, ALT=[G])

In [8]:
for record in lls.queryRegions([ (1, 1000000, 1001000), (2, 1000000, 1001000)], types=['snp']):
    print(record)

Record(CHROM=1, POS=1000760, REF=G, ALT=[A])
Record(CHROM=1, POS=1000797, REF=C, ALT=[T])
Record(CHROM=1, POS=1000854, REF=A, ALT=[C])
Record(CHROM=1, POS=1000857, REF=G, ALT=[T])
Record(CHROM=1, POS=1000894, REF=A, ALT=[T])
Record(CHROM=1, POS=1000902, REF=G, ALT=[A])
Record(CHROM=1, POS=1000910, REF=C, ALT=[T])
Record(CHROM=1, POS=1000987, REF=T, ALT=[C])
Record(CHROM=1, POS=1000990, REF=T, ALT=[G])
Record(CHROM=2, POS=1000024, REF=T, ALT=[C])
Record(CHROM=2, POS=1000029, REF=G, ALT=[A])
Record(CHROM=2, POS=1000127, REF=C, ALT=[T])
Record(CHROM=2, POS=1000192, REF=A, ALT=[T])
Record(CHROM=2, POS=1000283, REF=C, ALT=[T])
Record(CHROM=2, POS=1000738, REF=A, ALT=[G])
Record(CHROM=2, POS=1000918, REF=T, ALT=[A])

In [9]:
lls.queryRegions([ (1, 1000000, 1001000), (2, 1000000, 1001000)], types=['snp'], extract="summary")

               id   RR  R   RA  A  AA  O
0   1-1000760-G-A  221  0    1  0   0  0
1   1-1000797-C-T  218  0    1  0   0  3
2   1-1000854-A-C  214  0    1  0   0  7
3   1-1000857-G-T  212  0    1  0   0  9
4   1-1000894-A-T  214  0    7  0   0  1
5   1-1000902-G-A  221  0    1  0   0  0
6   1-1000910-C-T  172  0   39  0  11  0
7   1-1000987-T-C  221  0    1  0   0  0
8   1-1000990-T-G  221  0    1  0   0  0
9   2-1000024-T-C  212  0   10  0   0  0
10  2-1000029-G-A   61  0  110  0  51  0
11  2-1000127-C-T  172  0   48  0   2  0
12  2-1000192-A-T  221  0    1  0   0  0
13  2-1000283-C-T  165  0   55  0   2  0
14  2-1000738-A-G  194  0   27  0   1  0
15  2-1000918-T-A  220  0    2  0   0  0

### Querying the variants based on specific samples
The sample names provided in the VCF files of BBMRI are not the same as in the phenotypes file.
The names in the VCF have `'_240_37-ASM'` added at the end. To focus on only those, we must filter on them correctly.

In [17]:
relSamples = lls.phenotypes[(lls.phenotypes["sex"] == "MALE") & (lls.phenotypes["age"] > 100) ]
sampleFilters = relSamples["cgID"].apply(lambda x: x + '_240_37-ASM').values
sampleFilters

lls.queryRegions([ (1, 1000000, 1001000), (2, 1000000, 1001000)], types=['snp'], 
                 extract="summary", sampleFilters=sampleFilters)

               id  RR  R  RA  A  AA  O
0   1-1000760-G-A   5  0   0  0   0  0
1   1-1000797-C-T   5  0   0  0   0  0
2   1-1000854-A-C   4  0   0  0   0  1
3   1-1000857-G-T   4  0   0  0   0  1
4   1-1000894-A-T   5  0   0  0   0  0
5   1-1000902-G-A   5  0   0  0   0  0
6   1-1000910-C-T   3  0   1  0   1  0
7   1-1000987-T-C   5  0   0  0   0  0
8   1-1000990-T-G   5  0   0  0   0  0
9   2-1000024-T-C   5  0   0  0   0  0
10  2-1000029-G-A   1  0   3  0   1  0
11  2-1000127-C-T   3  0   2  0   0  0
12  2-1000192-A-T   5  0   0  0   0  0
13  2-1000283-C-T   4  0   1  0   0  0
14  2-1000738-A-G   5  0   0  0   0  0
15  2-1000918-T-A   5  0   0  0   0  0